# SwiftLint Configuration for Velociraptor macOS
# https://github.com/realm/SwiftLint

# Keep a minimal set of opt-in rules for code quality
opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - legacy_random
  - reduce_into
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - yoda_condition

# Disabled rules - keep linting focused on real issues
disabled_rules:
  - trailing_comma
  - force_cast
  - force_try
  - force_unwrap
  - identifier_name
  - line_length
  - todo
  - nesting
  - number_separator
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - single_test_class
  - trailing_closure
  - xct_specific_matcher
  - redundant_discardable_let
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - legacy_multiple
  - syntactic_sugar
  - for_where

# Paths to include
included:
  - VelociraptorMacOS
  - VelociraptorMacOSTests
  - VelociraptorMacOSUITests

# Paths to exclude
excluded:
  - VelociraptorMacOS/Resources
  - .build
  - Package.swift

# Rule configurations
function_parameter_count:
  warning: 8
  error: 10

large_tuple:
  warning: 5
  error: 7

type_name:
  min_length: 2
  max_length: 60
  allowed_symbols: ["_"]

vertical_whitespace:
  max_empty_lines: 3

colon:
  flexible_right_spacing: true

comma:
  severity: warning

statement_position:
  statement_mode: default

reporter: "xcode"
