# XcodeGen Project Specification
# Generate Xcode project: xcodegen generate
# Install XcodeGen: brew install xcodegen

name: VelociraptorMacOS
options:
  bundleIdPrefix: com.velocidex
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true
  developmentLanguage: en

packages:
  MCP:
    url: https://github.com/modelcontextprotocol/swift-sdk
    version: 0.7.1
  swift-log:
    url: https://github.com/apple/swift-log.git
    from: "1.4.0"

settings:
  base:
    MARKETING_VERSION: "5.0.5"
    CURRENT_PROJECT_VERSION: "1"
    PRODUCT_NAME: Velociraptor
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_IDENTITY: "-"
    INFOPLIST_FILE: VelociraptorMacOS/Info.plist
    CODE_SIGN_ENTITLEMENTS: VelociraptorMacOS/VelociraptorMacOS.entitlements
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    PRODUCT_BUNDLE_IDENTIFIER: com.velocidex.velociraptor
    COMBINE_HIDPI_IMAGES: YES
    LD_RUNPATH_SEARCH_PATHS:
      - "$(inherited)"
      - "@executable_path/../Frameworks"

targets:
  VelociraptorMacOS:
    type: application
    platform: macOS
    sources:
      - path: VelociraptorMacOS
        excludes:
          - "*.entitlements"
          - "TestingAgent/**"
    dependencies:
      - package: MCP
      - package: swift-log
        product: Logging
    settings:
      base:
        INFOPLIST_FILE: VelociraptorMacOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: VelociraptorMacOS/VelociraptorMacOS.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.velocidex.velociraptor
    entitlements:
      path: VelociraptorMacOS/VelociraptorMacOS.entitlements
    info:
      path: VelociraptorMacOS/Info.plist
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        basedOnDependencyAnalysis: false

  VelociraptorMacOSTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: VelociraptorMacOSTests
    dependencies:
      - target: VelociraptorMacOS
    settings:
      base:
        PRODUCT_NAME: VelociraptorTests
        PRODUCT_MODULE_NAME: VelociraptorTests
        PRODUCT_BUNDLE_IDENTIFIER: com.velocidex.velociraptor.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Velociraptor.app/Contents/MacOS/Velociraptor"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES

  VelociraptorMacOSUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: VelociraptorMacOSUITests
    dependencies:
      - target: VelociraptorMacOS
    settings:
      base:
        PRODUCT_NAME: VelociraptorUITests
        PRODUCT_MODULE_NAME: VelociraptorUITests
        PRODUCT_BUNDLE_IDENTIFIER: com.velocidex.velociraptor.uitests
        TEST_TARGET_NAME: VelociraptorMacOS
        GENERATE_INFOPLIST_FILE: YES

schemes:
  VelociraptorMacOS:
    build:
      targets:
        VelociraptorMacOS: all
        VelociraptorMacOSTests: [test]
        VelociraptorMacOSUITests: [test]
    run:
      config: Debug
      commandLineArguments:
        "-AppleLanguages": "(en)"
        "-AppleLocale": "en_US"
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - VelociraptorMacOS
      targets:
        - name: VelociraptorMacOSTests
          parallelizable: true
          randomExecutionOrder: true
        - name: VelociraptorMacOSUITests
          parallelizable: false
          randomExecutionOrder: false
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: true
