# SwiftLint Configuration for Velociraptor macOS
# https://github.com/realm/SwiftLint

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_comma
  - force_cast
  - force_try
  - identifier_name
  - line_length
  - todo
  - nesting

# Paths to include
included:
  - VelociraptorMacOS
  - VelociraptorMacOSTests
  - VelociraptorMacOSUITests

# Paths to exclude
excluded:
  - VelociraptorMacOS/Resources
  - .build
  - Package.swift

# Rule configurations
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 400
  error: 600

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

large_tuple:
  warning: 4
  error: 6

type_name:
  min_length: 3
  max_length: 50
  allowed_symbols: ["_"]

vertical_whitespace:
  max_empty_lines: 2

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

colon:
  flexible_right_spacing: true

comma:
  severity: warning

statement_position:
  statement_mode: default

# Custom rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: "\\bprint\\s*\\("
    message: "Use Logger.shared instead of print statements"
    severity: warning
    match_kinds:
      - identifier
  
  no_nslog:
    name: "No NSLog Statements"
    regex: "\\bNSLog\\s*\\("
    message: "Use Logger.shared instead of NSLog"
    severity: warning
    match_kinds:
      - identifier
  
  accessibility_required:
    name: "Accessibility Identifier"
    regex: "Button\\s*\\{[^}]*\\}\\s*\\.(?!accessibilityIdentifier)"
    message: "Buttons should have accessibility identifiers"
    severity: warning
    
  force_unwrap_in_tests_only:
    name: "Force Unwrap in Tests Only"
    regex: "![^=\\s]"
    message: "Force unwrap should only be used in test files"
    severity: warning
    excluded: ".*Tests\\.swift$"

reporter: "xcode"
